# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b1bf18dc30ffb41c7550eca3c49dbab777dc757d8997f188f8e86788b94045add92a7cd89bf69b4629cf80876c2feee5facfed07732bf5d91ebfdc0c0c3249d

test:
  secret_key_base: 2c15bd81c3c8f7b4e34849b179928864168dd43cc5624e41bb0d32264ac65f534c80ceeefa5ebbaa74bf23611af1315d7f50725f8a63e512b6d960f559462f33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
